# Generated by Django 4.2.4 on 2023-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=122)),
                ('fname', models.CharField(max_length=122)),
                ('mname', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('branch', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
            ],
        ),
    ]
