# Generated by Django 4.2.4 on 2023-08-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_address_admission_form_add_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_form',
            old_name='mothername',
            new_name='mname',
        ),
    ]
