# Generated by Django 4.2.4 on 2023-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_mothername_admission_form_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_form',
            name='date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
