# Generated by Django 4.2.4 on 2023-08-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_admission_form_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission_form',
            name='date',
        ),
    ]
