# Generated by Django 4.2.4 on 2023-08-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_admission_form_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
